
f1 = [
    ("O destino escreve nossa história", "Vida", "ria"),
    ("No jardim florescem esperanças", "Natureza", "ças"),
    ("Sorrisos iluminam a escuridão", "Felicidade", "ão"),
    ("As ondas sussurram segredos", "Mar", "dos"),
    ("O tempo apaga cicatrizes", "Reflexão", "zes"),
    ("A noite envolve os sonhos", "Sonhos", "hos"),
    ("No olhar brilha a esperança", "Sentimento", "ça"),
    ("O perfume das rosas encanta", "Natureza", "nta"),
    ("Caminhos se cruzam ao acaso", "Destino", "aso"),
    ("O vento leva as palavras", "Natureza", "vas"),
    ("A música embala a saudade", "Sentimento", "ade"),
    ("As montanhas tocam o céu", "Natureza", "céu"),
    ("O silêncio grita verdades", "Reflexão", "des"),
    ("Os pássaros anunciam a manhã", "Natureza", "hã"),
    ("O brilho do sol aquece", "Natureza", "ece"),
    ("A noite esconde mistérios", "Mistério", "ios"),
    ("O riso contagia os corações", "Felicidade", "ões"),
    ("O tempo ensina lições", "Vida", "ões"),
    ("A alma dança na liberdade", "Sentimento", "ade"),
    ("No inverno o frio abraça", "Estação", "ça"),
    ("As pegadas somem na areia", "Mar", "eia"),
    ("O destino sopra mudanças", "Destino", "ças"),
    ("A esperança brota no peito", "Sentimento", "ito"),
    ("Os versos guardam segredos", "Poesia", "dos"),
    ("O sol nasce em cada sonho", "Sonhos", "ho"),
    ("O abraço afasta a tristeza", "Sentimento", "za"),
    ("As lágrimas lavam a dor", "Reflexão", "dor"),
    ("O luar beija o oceano", "Natureza", "ano"),
    ("O céu reflete nossos desejos", "Sonhos", "jos"),
    ("A noite embala os amantes", "Amor", "tes"),
    ("As estrelas contam histórias", "Universo", "ias"),
    ("A luz dissipa as sombras", "Reflexão", "ras"),
    ("O mar esconde seus mistérios", "Mar", "ios"),
    ("O sorriso desarma a dor", "Felicidade", "dor"),
    ("O amor floresce na alma", "Amor", "lma"),
    ("A manhã traz um novo dia", "Tempo", "dia"),
    ("O vento espalha canções", "Natureza", "ões"),
    ("A estrada leva ao desconhecido", "Destino", "ido"),
    ("As nuvens dançam no céu", "Natureza", "céu"),
    ("A chuva beija a terra", "Natureza", "rra"),
    ("O fogo arde na paixão", "Amor", "ão"),
    ("O rio segue sem destino", "Natureza", "ino"),
    ("O brilho nos olhos revela", "Sentimento", "ela"),
    ("O tempo escreve cicatrizes", "Reflexão", "zes"),
    ("O amor se perde no tempo", "Amor", "mpo"),
    ("O destino guia os passos", "Destino", "sos"),
    ("As ondas quebram na areia", "Mar", "eia"),
    ("A liberdade dança no vento", "Sentimento", "nto"),
    ("As sombras escondem segredos", "Mistério", "dos"),
    ("A saudade mora no peito", "Sentimento", "ito"),
    ("O eco repete os medos", "Reflexão", "dos"),
    ("A luz brilha na escuridão", "Reflexão", "ão"),
    ("O sol despede-se do dia", "Natureza", "dia"),
    ("O coração bate esperança", "Sentimento", "ça"),
    ("As pegadas contam histórias", "Vida", "ias"),
    ("O olhar fala sem palavras", "Sentimento", "vas"),
    ("A vida dança ao acaso", "Destino", "aso"),
    ("A alma canta seus versos", "Poesia", "sos"),
    ("As estrelas piscam alegrias", "Universo", "ias"),
    ("A tempestade traz mudanças", "Reflexão", "ças"),
    ("O horizonte some no mar", "Natureza", "mar"),
    ("O tempo desvenda mistérios", "Reflexão", "ios"),
    ("O abraço é porto seguro", "Sentimento", "uro"),
    ("As folhas sussurram segredos", "Natureza", "dos"),
    ("A eternidade cabe num instante", "Tempo", "nte"),
    ("O amanhecer anuncia esperanças", "Natureza", "ças"),
    ("A lua inspira poesia", "Poesia", "sia"),
    ("O vento espalha lembranças", "Sentimento", "ças"),
    ("A sombra segue nossos passos", "Reflexão", "sos"),
    ("O calor do sol revigora", "Natureza", "ora"),
    ("O mar embala pensamentos", "Mar", "tos"),
    ("Os sonhos constroem futuros", "Sonhos", "ros"),
    ("O silêncio esconde palavras", "Reflexão", "vas"),
    ("As nuvens desenham ilusões", "Natureza", "ões"),
    ("O tempo esculpe destinos", "Destino", "nos"),
    ("O amor ilumina caminhos", "Amor", "hos"),
    ("A saudade é uma canção", "Sentimento", "ão"),
    ("A verdade brilha na alma", "Reflexão", "lma"),
    ("Os versos nascem no peito", "Poesia", "ito"),
    ("O amanhã guarda surpresas", "Destino", "sas"),
    ("O brilho da lua encanta", "Natureza", "nta"),
    ("O abraço dissolve tristezas", "Sentimento", "zas"),
    ("A poesia colore a vida", "Poesia", "ida"),
    ("O olhar reflete a alma", "Sentimento", "lma"),
    ("O dia se despede suave", "Tempo", "ave"),
    ("A estrada segue sem fim", "Destino", "fim"),
    ("No horizonte brilha a lua", "Natureza", "lua"),
    ("O amor floresce sem aviso", "Amor", "iso"),
    ("O vento dança entre as folhas", "Natureza", "has"),
    ("Sonhos ecoam na madrugada", "Sonhos", "ada"),
    ("O destino escreve sua estrada", "Vida", "ada"),
    ("Sorrisos brilham como o sol", "Felicidade", "sol"),
    ("A dor ensina com paixão", "Reflexão", "ão"),
    ("As estrelas piscam no céu", "Universo", "éu"),
    ("O sol renasce toda manhã", "Natureza", "hã"),
    ("A saudade dança na memória", "Sentimento", "ria"),
    ("Os sonhos pintam o infinito", "Sonhos", "ito"),
    ("A brisa leve beija o rosto", "Natureza", "sto"),
    ("No silêncio brota a paz", "Reflexão", "paz"),
    ("O rio segue sem olhar atrás", "Natureza", "raz"),
    ("Os olhos falam sem palavras", "Sentimento", "vas"),
    ("A felicidade brilha no riso", "Felicidade", "iso"),
    ("A lua abraça a escuridão", "Universo", "ão"),
    ("O destino traça surpresas", "Destino", "sas"),
    ("As estrelas bordam a noite", "Universo", "ite"),
    ("O vento canta em liberdade", "Natureza", "ade"),
    ("As folhas caem em despedida", "Natureza", "ida"),
    ("O mar embala nossos sonhos", "Mar", "hos"),
    ("O amor floresce em cada olhar", "Amor", "har"),
    ("O tempo leva e traz memórias", "Vida", "ias"),
    ("O coração pulsa em sintonia", "Sentimento", "nia"),
    ("A esperança nasce no peito", "Sentimento", "ito"),
    ("O sol aquece até a alma", "Natureza", "lma"),
    ("A vida é feita de instantes", "Reflexão", "tes"),
    ("O amanhecer traz novos rumos", "Tempo", "mos"),
    ("Os versos dançam no papel", "Poesia", "pel"),
    ("A chuva canta sobre a terra", "Natureza", "rra"),
    ("O olhar revela o infinito", "Sentimento", "ito"),
    ("O dia se despede em luz", "Tempo", "luz"),
    ("O tempo apaga cicatrizes", "Reflexão", "zes"),
    ("A esperança colore o mundo", "Sentimento", "ndo"),
    ("O amor é chama que não se apaga", "Amor", "aga"),
    ("O vento sopra novas histórias", "Destino", "ias"),
    ("O rio murmura antigas canções", "Natureza", "ões"),
    ("A lua ilumina os apaixonados", "Amor", "dos"),
    ("A liberdade voa como um pássaro", "Sentimento", "ro"),
    ("O silêncio guarda segredos", "Reflexão", "dos"),
    ("As pegadas marcam o caminho", "Vida", "lho"),
    ("O coração transborda emoção", "Sentimento", "ão"),
    ("As estrelas piscam esperança", "Universo", "ça"),
    ("O dia amanhece com promessas", "Tempo", "sas"),
    ("A brisa espalha lembranças", "Natureza", "ças"),
    ("O céu reflete nossos sonhos", "Universo", "hos"),
    ("A tempestade precede a calmaria", "Natureza", "ria"),
    ("O abraço dissolve a distância", "Sentimento", "cia"),
    ("O olhar esconde universos", "Sentimento", "sos"),
    ("As ondas cantam sobre a areia", "Mar", "eia"),
    ("O tempo molda nossa essência", "Vida", "cia"),
    ("A poesia nasce do sentir", "Poesia", "tir"),
    ("O amor acalma o desespero", "Amor", "ero"),
    ("A noite inspira pensamentos", "Reflexão", "tos"),
    ("O dia se despede suave", "Tempo", "ave"),
    ("O vento leva os medos", "Natureza", "dos"),
    ("A alma dança em liberdade", "Sentimento", "ade"),
    ("A manhã beija a terra", "Natureza", "rra"),
    ("O destino brinca com os sonhos", "Destino", "hos"),
    ("A lua sussurra mistérios", "Universo", "ios"),
    ("O sol despede-se no horizonte", "Natureza", "nte"),
    ("Os olhos guardam promessas", "Sentimento", "sas"),
    ("O eco traz vozes do passado", "Reflexão", "ado"),
    ("O riso ilumina a escuridão", "Felicidade", "ão"),
    ("O tempo ensina sem pressa", "Reflexão", "ssa"),
    ("A saudade canta baixinho", "Sentimento", "nho"),
    ("O mar abraça os viajantes", "Mar", "tes"),
    ("A estrada se estende sem fim", "Destino", "fim"),
    ("A esperança caminha entre nós", "Sentimento", "ós"),
    ("A tempestade dança no céu", "Natureza", "céu"),
    ("Os versos ecoam na alma", "Poesia", "lma"),
    ("O futuro se faz no presente", "Tempo", "nte"),
    ("O amor cresce como semente", "Amor", "nte"),
    ("Os astros guiam a noite", "Universo", "ite"),
    ("O vento sopra entre as folhas", "Natureza", "has"),
    ("O mar guarda histórias antigas", "Mar", "gas"),
    ("A liberdade mora no olhar", "Sentimento", "har"),
    ("O brilho do sol revigora", "Natureza", "ora"),
    ("As nuvens desenham esperanças", "Natureza", "ças"),
    ("Os sonhos renascem na alvorada", "Sonhos", "ada"),
    ("O tempo desvenda mistérios", "Reflexão", "ios"),
    ("A luz dissipa o medo", "Reflexão", "edo"),
    ("A verdade brilha na alma", "Reflexão", "lma"),
    ("O destino escreve sua rota", "Destino", "ota"),
    ("O silêncio acolhe pensamentos", "Reflexão", "tos"),
    ("O amor reflete o infinito", "Amor", "ito"),
    ("A vida pulsa no coração", "Vida", "ão"),
    ("A chuva lava a tristeza", "Natureza", "za"),
    ("A lua ilumina o caminho", "Universo", "nho"),
    ("A fé renova o espírito", "Sentimento", "ito"),
    ("O tempo desenha cicatrizes", "Reflexão", "zes"),
    ("A estrada ensina lições", "Destino", "ões"),
    ("O riso espanta a solidão", "Felicidade", "ão"),
    ("Os ventos mudam direções", "Natureza", "ões"),
    ("O passado ecoa no presente", "Tempo", "nte"),
    ("Os olhos refletem sentimentos", "Sentimento", "tos"),
    ("O horizonte chama pelo amanhã", "Destino", "hã"),
    ("A eternidade cabe num instante", "Tempo", "nte"),
    ("O vento sopra e leva a dor", "Natureza", "dor"),
    ("A lua brilha no céu azul", "Universo", "zul"),
    ("As estrelas piscam sem cessar", "Universo", "sar"),
    ("O amor renasce a cada dia", "Amor", "dia"),
    ("A chuva canta no telhado", "Natureza", "ado"),
    ("O tempo voa como um pássaro", "Vida", "ro"),
    ("O destino dança entre nós", "Destino", "nós"),
    ("O mar sussurra canções antigas", "Mar", "gas"),
    ("Os sonhos voam na madrugada", "Sonhos", "ada"),
    ("A felicidade mora no instante", "Felicidade", "nte"),
    ("O silêncio abraça a noite", "Reflexão", "ite"),
    ("O sol se despede no horizonte", "Natureza", "nte"),
    ("O abraço aquece o coração", "Sentimento", "ão"),
    ("A esperança ilumina a alma", "Sentimento", "lma"),
    ("A saudade canta na distância", "Sentimento", "cia"),
    ("Os olhos guardam mil histórias", "Sentimento", "ias"),
    ("O riso colore os dias", "Felicidade", "ias"),
    ("A liberdade dança no vento", "Sentimento", "nto"),
    ("A noite guarda mistérios", "Mistério", "ios"),
    ("A estrada leva para longe", "Destino", "nge"),
    ("O eco repete a solidão", "Reflexão", "ão"),
    ("A lua inspira os amantes", "Amor", "tes"),
    ("O dia amanhece com promessas", "Tempo", "sas"),
    ("O tempo revela verdades", "Reflexão", "des"),
    ("O destino segue seu curso", "Destino", "rso"),
    ("A música embala os sonhos", "Sonhos", "hos"),
    ("O olhar traduz sentimentos", "Sentimento", "tos"),
    ("O brilho do sol aquece", "Natureza", "ece"),
    ("As ondas quebram na praia", "Mar", "aia"),
    ("O vento espalha lembranças", "Reflexão", "ças"),
    ("A poesia nasce no coração", "Poesia", "ão"),
    ("As pegadas somem na areia", "Mar", "eia"),
    ("O dia termina em cores", "Natureza", "res"),
    ("A tempestade traz renascimento", "Reflexão", "nto"),
    ("O amanhã traz novas chances", "Tempo", "ces"),
    ("A esperança mora no peito", "Sentimento", "ito"),
    ("A luz dissipa as sombras", "Reflexão", "ras"),
    ("O destino traça novos caminhos", "Destino", "hos"),
        ("A vida floresce em cada novo dia", "Vida", "ia"),
    ("Os caminhos se cruzam e se perdem", "Vida", "dem"),
    ("Cada instante é um presente divino", "Vida", "ino"),
    ("No pulsar do tempo, tudo renasce", "Vida", "sce"),
    ("O destino se molda em nossas mãos", "Vida", "ãos"),
    ("Teus passos pequenos seguem os meus", "Filho", "eus"),
    ("No teu sorriso vejo meu reflexo", "Filho", "exo"),
    ("Cada abraço teu me faz mais forte", "Filho", "rte"),
    ("Filho, és a luz do meu caminho", "Filho", "nho"),
    ("Teus olhos brilham como estrelas", "Filho", "las"),
    ("Os sonhos voam em asas de ouro", "Sonhos", "uro"),
    ("A esperança dorme em nossos desejos", "Sonhos", "jos"),
    ("Cada sonho é um mundo secreto", "Sonhos", "eto"),
    ("No silêncio da noite, eles despertam", "Sonhos", "tam"),
    ("Os sonhos iluminam a estrada escura", "Sonhos", "ura"),
    ("As cinzas dançam ao sopro do vento", "Morte", "ento"),
    ("O silêncio é o último abraço", "Morte", "ço"),
    ("As lápides contam histórias esquecidas", "Morte", "das"),
    ("A morte caminha sem pressa, serena", "Morte", "ena"),
    ("Sombras sussurram nomes do passado", "Morte", "ado"),
    ("O brilho do dia reflete em sorrisos", "Alegria", "sos"),
    ("O vento carrega gargalhadas livres", "Alegria", "ves"),
    ("A felicidade é um pássaro no céu", "Alegria", "éu"),
    ("Cada riso espalha cores pelo ar", "Alegria", "ar"),
    ("O coração dança ao som da esperança", "Alegria", "ça"),
    ("As lágrimas caem sem rumo no chão", "Tristeza", "ão"),
    ("A saudade aperta como um nó", "Tristeza", "ó"),
    ("O frio envolve a alma vazia", "Tristeza", "ia"),
    ("O adeus ecoa em ruas desertas", "Tristeza", "tas"),
    ("A dor se esconde no silêncio", "Tristeza", "ço"),
    ("Os cacos do amor brilham no escuro", "Coração Partido", "uro"),
    ("Teu nome ainda vive no meu peito", "Coração Partido", "to"),
    ("As promessas ficaram no vento", "Coração Partido", "to"),
    ("O amor partiu sem olhar para trás", "Coração Partido", "ás"),
    ("O tempo não apaga cicatrizes", "Coração Partido", "zes"),
    ("O eco responde minha própria dor", "Solidão", "dor"),
    ("Os dias passam sem companhia", "Solidão", "ia"),
    ("O vento sopra um frio sem fim", "Solidão", "fim"),
    ("A lua escuta meu pranto calado", "Solidão", "ado"),
    ("Os passos ressoam na rua vazia", "Solidão", "ia"),
    ("O guerreiro levanta da queda", "Animes", "eda"),
    ("A jornada só termina no fim", "Animes", "fim"),
    ("Os olhos brilham com determinação", "Animes", "ão"),
    ("O destino traça caminhos incertos", "Animes", "tos"),
    ("A batalha molda heróis eternos", "Animes", "nos"),
    ("O pôr do sol colore o horizonte", "Beleza", "nte"),
    ("Os olhos refletem a luz da alma", "Beleza", "lma"),
    ("Tua essência é um jardim florido", "Beleza", "ido"),
    ("A beleza se esconde nos detalhes", "Beleza", "hes"),
    ("A arte da vida mora no olhar", "Beleza", "ar"),
    ("Os segundos dançam sem parar", "Tempo", "ar"),
    ("O relógio avança sem compaixão", "Tempo", "ão"),
    ("O tempo escreve histórias na pele", "Tempo", "ele"),
    ("Cada instante é um presente divino", "Tempo", "ino"),
    ("O passado ecoa em nossa memória", "Tempo", "ria"),
    ("O abraço materno cura feridas", "Amor de Mãe", "das"),
    ("O olhar de mãe acalma tempestades", "Amor de Mãe", "des"),
    ("O amor materno é laço sem fim", "Amor de Mãe", "fim"),
    ("Cada palavra sua é proteção", "Amor de Mãe", "ão"),
    ("Tua voz embala meus sonhos", "Amor de Mãe", "hos"),
    ("O amor sussurra promessas no vento", "Romântico", "to"),
    ("Teus olhos brilham como estrelas", "Romântico", "las"),
    ("Cada toque teu é um verso eterno", "Romântico", "rno"),
    ("O mundo some no teu abraço", "Romântico", "ço"),
    ("Nosso amor é um doce infinito", "Romântico", "ito"),
    ("O azul do céu abraça a alma", "Céu", "lma"),
    ("As nuvens desenham sonhos no ar", "Céu", "ar"),
    ("O pôr do sol queima no horizonte", "Céu", "nte"),
    ("As estrelas piscam segredos antigos", "Céu", "gos"),
    ("A lua vigia o silêncio da noite", "Céu", "ite"),
    ("O mar canta canções esquecidas", "Mar", "das"),
    ("As ondas quebram sem nunca cansar", "Mar", "ar"),
    ("O vento traz o cheiro de sal", "Mar", "sal"),
    ("O horizonte se perde no azul", "Mar", "zul"),
    ("A brisa do mar embala meus sonhos", "Mar", "hos"),
    ("A vida segue caminhos incertos", "Vida", "tos"),
    ("Cada dia é um presente sagrado", "Vida", "ado"),
    ("A esperança renasce a cada aurora", "Vida", "ora"),
    ("O tempo ensina lições valiosas", "Vida", "sas"),
    ("No pulsar do coração, vive o universo", "Vida", "rso"),
    ("Teus passos pequenos seguem os meus", "Filho", "eus"),
    ("No teu sorriso vejo meu reflexo", "Filho", "exo"),
    ("Cada abraço teu me faz mais forte", "Filho", "rte"),
    ("Filho, és a luz do meu caminho", "Filho", "nho"),
    ("Teus olhos brilham como estrelas", "Filho", "las"),
    ("Os sonhos voam em asas de ouro", "Sonhos", "uro"),
    ("A esperança dorme em nossos desejos", "Sonhos", "jos"),
    ("Cada sonho é um mundo secreto", "Sonhos", "eto"),
    ("No silêncio da noite, eles despertam", "Sonhos", "tam"),
    ("Os sonhos iluminam a estrada escura", "Sonhos", "ura"),
    # Solidão
    ("O silêncio me envolve sem pressa", "Solidão", "ssa"),
    ("A noite escura abraça meu ser", "Solidão", "ser"),
    ("Os passos ecoam na rua vazia", "Solidão", "ia"),
    ("A lua é minha única testemunha", "Solidão", "ha"),
    ("As sombras dançam ao meu redor", "Solidão", "dor"),
    
    # Animes
    ("A jornada do herói nunca termina", "Animes", "ina"),
    ("A espada brilha sob a lua cheia", "Animes", "eia"),
    ("O guerreiro enfrenta seu destino", "Animes", "ino"),
    ("A batalha pulsa em cada coração", "Animes", "ão"),
    ("O poder desperta na escuridão", "Animes", "ão"),
    
    # Beleza
    ("O brilho dos teus olhos me encanta", "Beleza", "nta"),
    ("Cada detalhe teu é um poema", "Beleza", "ema"),
    ("Tua presença ilumina o dia", "Beleza", "ia"),
    ("O mundo se curva à tua graça", "Beleza", "ça"),
    ("Tua voz é música para minha alma", "Beleza", "lma"),
    
    # Tempo
    ("O tempo escreve histórias eternas", "Tempo", "nas"),
    ("Cada segundo é um presente vivo", "Tempo", "ivo"),
    ("As horas se perdem como folhas", "Tempo", "has"),
    ("O relógio marca um novo começo", "Tempo", "ço"),
    ("O passado sussurra em cada esquina", "Tempo", "ina"),
    
    # Amor de Mãe
    ("O colo materno é abrigo seguro", "Amor de Mãe", "uro"),
    ("Tua voz acalma qualquer dor", "Amor de Mãe", "dor"),
    ("O amor de mãe é luz infinita", "Amor de Mãe", "ita"),
    ("Teu carinho é sol na tempestade", "Amor de Mãe", "ade"),
    ("No teu abraço, encontro o mundo", "Amor de Mãe", "ndo"),
    
    # Vida
    ("A vida se reinventa a cada dia", "Vida", "ia"),
    ("Os sonhos constroem a existência", "Vida", "cia"),
    ("No pulsar do tempo, tudo muda", "Vida", "uda"),
    ("A estrada da vida é sempre incerta", "Vida", "rta"),
    ("O destino se molda em nossas mãos", "Vida", "ãos"),
    
    # Natureza
    ("O orvalho brilha sobre a relva", "Natureza", "va"),
    ("O vento sopra segredos antigos", "Natureza", "gos"),
    ("A tempestade dança no horizonte", "Natureza", "nte"),
    ("Os rios correm sem olhar para trás", "Natureza", "ás"),
    ("O sol beija o mar no entardecer", "Natureza", "cer"),
    ("As montanhas sussurram histórias", "Natureza", "ias"),
    ("As árvores abraçam o infinito", "Natureza", "ito"),
    ("A lua vela o mundo adormecido", "Natureza", "ido"),
    ("Os pássaros cantam ao amanhecer", "Natureza", "cer"),
    ("Cada folha guarda um segredo", "Natureza", "edo"),
    
    # Amor
    ("Teus lábios trazem promessas doces", "Amor", "ces"),
    ("Nosso olhar se cruza e o tempo para", "Amor", "ara"),
    ("O amor floresce em cada abraço", "Amor", "ço"),
    ("No teu sorriso encontro a paz", "Amor", "az"),
    ("Teus braços são meu lar eterno", "Amor", "rno"),
    ("Nosso amor desafia o destino", "Amor", "ino"),
    ("Em teu beijo, o mundo se dissolve", "Amor", "ve"),
    ("Te amo além do tempo e do espaço", "Amor", "ço"),
    ("Nosso amor é chama sempre viva", "Amor", "iva"),
    ("O amor nos guia como estrelas", "Amor", "las"),
    
    # Flor
    ("O campo se enfeita de margaridas", "Flor", "das"),
    ("As rosas se abrem ao toque do sol", "Flor", "sol"),
    ("Cada pétala guarda uma história", "Flor", "ria"),
    ("A primavera veste-se de cores", "Flor", "res"),
    ("Os girassóis dançam sob o azul", "Flor", "zul"),
    ("A brisa espalha o perfume das flores", "Flor", "res"),
    ("O jardim sorri ao amanhecer", "Flor", "cer"),
    ("As violetas guardam segredos leves", "Flor", "ves"),
    ("Cada flor tem sua poesia única", "Flor", "ica"),
    ("O aroma das flores acalma a alma", "Flor", "lma"),
    
    # Morte
    ("O silêncio acompanha o último suspiro", "Morte", "iro"),
    ("A saudade se espalha como sombras", "Morte", "bras"),
    ("Cada adeus é um fio de tempo partido", "Morte", "ido"),
    ("O vento carrega vozes que se foram", "Morte", "ram"),
    ("As lembranças se apagam como cinzas", "Morte", "zas"),
    ("O tempo enterra histórias não contadas", "Morte", "das"),
    ("O fim chega na curva do destino", "Morte", "ino"),
    ("A noite abraça os que se despedem", "Morte", "dem"),
    ("As lápides guardam nomes esquecidos", "Morte", "dos"),
    ("A morte sussurra em voz serena", "Morte", "ena"),
    
    # Alegria
    ("O riso ilumina os dias cinzentos", "Alegria", "tos"),
    ("Cada sorriso traz um raio de sol", "Alegria", "sol"),
    ("A felicidade dança em nossos passos", "Alegria", "sos"),
    ("Os sonhos explodem em cores vivas", "Alegria", "vas"),
    ("O vento canta canções de esperança", "Alegria", "ça"),
    ("A alegria se espalha como perfume", "Alegria", "ume"),
    ("O mundo sorri com olhos brilhantes", "Alegria", "tes"),
    ("A luz da manhã traz novas promessas", "Alegria", "sas"),
    ("O tempo se curva ao encanto da vida", "Alegria", "ida"),
    ("A felicidade é um barco ao vento", "Alegria", "ento"),
    # Morte
    ("A noite desce como um véu eterno", "Morte", "rno"),
    ("Os suspiros findam na escuridão", "Morte", "ão"),
    ("O último adeus ecoa no tempo", "Morte", "po"),
    ("As sombras guardam segredos antigos", "Morte", "gos"),
    ("A despedida dança no vento frio", "Morte", "rio"),
    
    # Alegria
    ("O riso brota feito flor no campo", "Alegria", "po"),
    ("As cores saltam em festa brilhante", "Alegria", "nte"),
    ("O sol desperta sorrisos no rosto", "Alegria", "sto"),
    ("A felicidade canta em cada passo", "Alegria", "so"),
    ("Nos olhos brilham estrelas de festa", "Alegria", "ta"),
    
    # Tristeza
    ("A lágrima cai sem pedir licença", "Tristeza", "ça"),
    ("O silêncio pesa no peito vazio", "Tristeza", "io"),
    ("Cada lembrança é um eco perdido", "Tristeza", "ido"),
    ("Os dias frios abraçam minha dor", "Tristeza", "dor"),
    ("A noite esconde segredos sombrios", "Tristeza", "ios"),
    # Coração Partido
    ("O amor se foi sem deixar vestígios", "Coração Partido", "ios"),
    ("As promessas quebraram-se ao vento", "Coração Partido", "to"),
    ("Os beijos viraram memórias distantes", "Coração Partido", "tes"),
    ("O coração chora em silêncio profundo", "Coração Partido", "do"),
    ("A saudade queima feito chama viva", "Coração Partido", "iva"),
    # Solidão
    ("As sombras dançam em meu quarto frio", "Solidão", "rio"),
    ("O eco responde minha própria voz", "Solidão", "oz"),
    ("Caminho sozinho por ruas vazias", "Solidão", "ias"),
    ("O vento abraça meu corpo cansado", "Solidão", "ado"),
    ("A noite é minha única companhia", "Solidão", "ia"),
    # Animes
    ("O herói levanta após cada queda", "Animes", "eda"),
    ("O destino se escreve com batalhas", "Animes", "has"),
    ("Os sonhos voam em asas de fogo", "Animes", "ogo"),
    ("O guerreiro segue seu caminho solitário", "Animes", "rio"),
    ("A força desperta no momento final", "Animes", "nal"),
    # Beleza
    ("A lua reflete tua graça divina", "Beleza", "ina"),
    ("Cada detalhe teu é poesia viva", "Beleza", "iva"),
    ("Teus olhos guardam um brilho encantado", "Beleza", "ado"),
    ("O mundo se curva ao teu caminhar", "Beleza", "har"),
    ("Tua voz é um canto doce e suave", "Beleza", "ave"),
    # Tempo
    ("O relógio avança sem olhar atrás", "Tempo", "ás"),
    ("Cada segundo traz um novo começo", "Tempo", "ço"),
    ("As horas escorrem como fina areia", "Tempo", "eia"),
    ("O tempo esculpe rugas na memória", "Tempo", "ria"),
    ("No tempo perdido, encontro saudade", "Tempo", "ade"),
    # Amor de Mãe
    ("Tuas mãos afagam cada dor minha", "Amor de Mãe", "nha"),
    ("O amor materno é luz infinita", "Amor de Mãe", "ita"),
    ("No teu abraço, a paz é completa", "Amor de Mãe", "eta"),
    ("Tua voz embala meus sonhos serenos", "Amor de Mãe", "nos"),
    ("Mãe, és estrela que nunca se apaga", "Amor de Mãe", "aga"),
    # Romântico
    ("Teu beijo tem gosto de eternidade", "Romântico", "ade"),
    ("Nos teus braços, esqueço o mundo", "Romântico", "ndo"),
    ("Teus olhos são meu céu estrelado", "Romântico", "ado"),
    ("Cada suspiro teu é uma melodia", "Romântico", "ia"),
    ("Nosso amor é um conto sem fim", "Romântico", "fim"),
    
    # Céu
    ("O azul infinito abraça meus sonhos", "Céu", "hos"),
    ("As nuvens dançam como folhas leves", "Céu", "ves"),
    ("Cada estrela é um desejo guardado", "Céu", "ado"),
    ("O sol se despede em tons dourados", "Céu", "dos"),
    ("A lua sorri no espelho do mar", "Céu", "mar"),
    
    # Mar
    ("O mar canta segredos ao vento", "Mar", "ento"),
    ("As ondas desenham versos na areia", "Mar", "eia"),
    ("O horizonte se perde no azul", "Mar", "zul"),
    ("O sal da brisa beija minha pele", "Mar", "ele"),
    ("As águas dançam em ritmo eterno", "Mar", "rno"),
    
]