
f3 = [
    ("Os versos dançam no papel", "Poesia", "pel"),
    ("A estrada chama aventureiros", "Destino", "ros"),
    ("A neblina cobre a cidade", "Natureza", "ade"),
    ("A paixão arde como fogo", "Amor", "ogo"),
    ("O passado repousa sereno", "Reflexão", "eno"),
    ("O abraço dissolve os medos", "Sentimento", "dos"),
    ("Os dias pintam novas cores", "Tempo", "res"),
    ("A fé constrói fortalezas", "Reflexão", "zas"),
    ("O tempo sussurra verdades", "Reflexão", "des"),
    ("A chuva lava as lembranças", "Natureza", "ças"),
    ("A lua espelha os desejos", "Universo", "jos"),
    ("O coração canta baixinho", "Sentimento", "nho"),
    ("O silêncio envolve a alma", "Reflexão", "lma"),
    ("O destino sopra mistérios", "Destino", "ios"),
    ("As ondas moldam a praia", "Mar", "aia"),
    ("A brisa traz leveza", "Natureza", "eza"),
    ("Os astros tecem histórias", "Universo", "ias"),
    ("O dia clareia esperanças", "Natureza", "ças"),
    ("As palavras desenham poesia", "Poesia", "sia"),
    ("O riso ilumina o escuro", "Felicidade", "uro"),
    ("A sombra esconde o passado", "Mistério", "ado"),
    ("O céu acolhe os sonhos", "Universo", "hos"),
    ("Os olhos guardam lembranças", "Sentimento", "ças"),
    ("O vento embala os sentidos", "Natureza", "dos"),
    ("O amor tece destinos", "Amor", "nos"),
    ("O caminho ensina paciência", "Destino", "cia"),
    ("A estrada revela promessas", "Destino", "sas"),
    ("Os lábios sussurram segredos", "Sentimento", "dos"),
    ("O luar desenha fantasias", "Universo", "ias"),
    ("O dia se despede calado", "Natureza", "ado"),
    ("O tempo apaga cicatrizes", "Reflexão", "zes"),
    ("Os sinos anunciam mudanças", "Tempo", "ças"),
    ("A verdade dança na alma", "Reflexão", "lma"),
    ("A paixão se espalha no vento", "Amor", "ento"),
    ("A paz floresce no coração", "Sentimento", "ão"),
    ("Os sorrisos curam feridas", "Felicidade", "das"),
    ("A neblina esconde os passos", "Natureza", "sos"),
    ("O trovão rompe o silêncio", "Natureza", "cio"),
    ("O tempo resgata memórias", "Reflexão", "ias"),
    ("O mar guarda antigos segredos", "Mar", "dos"),
    ("O destino sopra certezas", "Destino", "zas"),
    ("O pôr do sol colore esperanças", "Natureza", "ças"),
    ("As noites abraçam o mistério", "Universo", "rio"),
    ("O silêncio sussurra verdades", "Reflexão", "des"),
    ("A estrada se perde na bruma", "Destino", "uma"),
    ("O olhar traduz emoções", "Sentimento", "ões"),
    ("O tempo reconstrói histórias", "Reflexão", "ias"),
    ("O vento traz recordações", "Natureza", "ões"),
    ("O amor se espalha no espaço", "Amor", "ço"),
    ("O sol brilha entre os galhos", "Natureza", "lhos"),
    ("A lua dança com as estrelas", "Universo", "las"),
    ("O destino escreve com vento", "Destino", "ento"),
    ("O silêncio revela a essência", "Reflexão", "cia"),
    ("O tempo ensina com paciência", "Reflexão", "cia"),
    ("Os passos ecoam na estrada", "Destino", "ada"),
    ("O céu abraça a imensidão", "Universo", "ão"),
    ("O amor aquece em qualquer estação", "Amor", "ção"),
    ("A esperança brota como flor", "Sentimento", "lor"),
    ("As marés contam sua história", "Mar", "ria"),
    ("O destino traça caminhos", "Destino", "hos"),
    ("As folhas dançam ao vento", "Natureza", "ento"),
    ("O coração pulsa forte", "Sentimento", "rte"),
    ("Os astros guiam a jornada", "Universo", "ada"),
    ("O tempo renova as dores", "Reflexão", "res"),
    ("A brisa refresca a pele", "Natureza", "ele"),
    ("O horizonte se desfaz em cores", "Natureza", "res"),
    ("Os sorrisos aquecem a alma", "Felicidade", "lma"),
    ("A chuva traz lembranças antigas", "Natureza", "gas"),
    ("Brisa toca leve a pele", "Natureza", "ele"),
    ("Sol renasce a cada dia", "Natureza", "dia"),
    ("Noite esconde os segredos", "Mistério", "dos"),
    ("Mar canta versos antigos", "Mar", "gos"),
    ("Olhos refletem memórias", "Reflexão", "ias"),
    ("Chuva embala os corações", "Natureza", "ões"),
    ("Vento sussurra baixinho", "Natureza", "nho"),
    ("Estrelas brilham em festa", "Universo", "sta"),
    ("Tempo dança sem parar", "Reflexão", "rar"),
    ("Esperança acende caminhos", "Sentimento", "hos"),
    ("Saudade grita no peito", "Sentimento", "ito"),
    ("Riso ilumina a jornada", "Felicidade", "ada"),
    ("Lua observa em silêncio", "Universo", "cio"),
    ("Dias correm apressados", "Tempo", "dos"),
    ("Sombras falam baixinho", "Mistério", "nho"),
    ("Amor floresce na calma", "Amor", "lma"),
    ("Destino traça mistérios", "Destino", "ios"),
    ("Pássaros cantam a aurora", "Natureza", "ora"),
    ("Olhar atravessa distâncias", "Sentimento", "cias"),
    ("Mar esconde seus segredos", "Mar", "dos"),
    ("Sonhos tocam o infinito", "Sonhos", "ito"),
    ("Alma respira esperança", "Sentimento", "ça"),
    ("Vento espalha promessas", "Natureza", "sas"),
    ("Pegadas somem na areia", "Natureza", "eia"),
    ("Sol aquece a memória", "Natureza", "ria"),
    ("Noite beija o horizonte", "Universo", "nte"),
    ("Tempestade traz mudanças", "Natureza", "ças"),
    ("Eco repete solidão", "Reflexão", "ão"),
    ("Versos dançam no papel", "Poesia", "pel"),
    ("Estrada chama aventureiros", "Destino", "ros"),
    ("Neblina cobre a cidade", "Natureza", "ade"),
    ("Paixão arde como fogo", "Amor", "ogo"),
    ("Passado repousa sereno", "Reflexão", "eno"),
    ("Abraço dissolve os medos", "Sentimento", "dos"),
    ("Dias pintam novas cores", "Tempo", "res"),
    ("Fé constrói fortalezas", "Reflexão", "zas"),
    ("Tempo sussurra verdades", "Reflexão", "des"),
    ("Chuva lava as lembranças", "Natureza", "ças"),
    ("Lua espelha os desejos", "Universo", "jos"),
    ("Coração canta baixinho", "Sentimento", "nho"),
    ("Silêncio envolve a alma", "Reflexão", "lma"),
    ("Destino sopra mistérios", "Destino", "ios"),
    ("Ondas moldam a praia", "Mar", "aia"),
    ("Brisa traz leveza", "Natureza", "eza"),
    ("Astros tecem histórias", "Universo", "ias"),
    ("Dia clareia esperanças", "Natureza", "ças"),
    ("Palavras desenham poesia", "Poesia", "sia"),
    ("Riso ilumina o escuro", "Felicidade", "uro"),
    ("Sombra esconde o passado", "Mistério", "ado"),
    ("Céu acolhe os sonhos", "Universo", "hos"),
    ("Olhos guardam lembranças", "Sentimento", "ças"),
    ("Vento embala os sentidos", "Natureza", "dos"),
    ("Amor tece destinos", "Amor", "nos"),
    ("Caminho ensina paciência", "Destino", "cia"),
    ("Estrada revela promessas", "Destino", "sas"),
    ("Lábios sussurram segredos", "Sentimento", "dos"),
    ("Luar desenha fantasias", "Universo", "ias"),
    ("Dia se despede calado", "Natureza", "ado"),
    ("Tempo apaga cicatrizes", "Reflexão", "zes"),
    ("Sinos anunciam mudanças", "Tempo", "ças"),
    ("Verdade dança na alma", "Reflexão", "lma"),
    ("Paixão se espalha no vento", "Amor", "ento"),
    ("Paz floresce no coração", "Sentimento", "ão"),
    ("Sorrisos curam feridas", "Felicidade", "das"),
    ("Neblina esconde os passos", "Natureza", "sos"),
    ("Trovão rompe o silêncio", "Natureza", "cio"),
    ("Tempo resgata memórias", "Reflexão", "ias"),
    ("Mar guarda antigos segredos", "Mar", "dos"),
    ("Destino sopra certezas", "Destino", "zas"),
    ("Pôr do sol colore esperanças", "Natureza", "ças"),
    ("Noites abraçam o mistério", "Universo", "rio"),
    ("Silêncio sussurra verdades", "Reflexão", "des"),
    ("Estrada se perde na bruma", "Destino", "uma"),
    ("Olhar traduz emoções", "Sentimento", "ões"),
    ("Tempo reconstrói histórias", "Reflexão", "ias"),
    ("Vento traz recordações", "Natureza", "ões"),
    ("Amor se espalha no espaço", "Amor", "ço"),
    ("Sol brilha entre os galhos", "Natureza", "lhos"),
    ("Lua dança com as estrelas", "Universo", "las"),
    ("Destino escreve com vento", "Destino", "ento"),
    ("Silêncio revela a essência", "Reflexão", "cia"),
    ("Tempo ensina com paciência", "Reflexão", "cia"),
    ("Passos ecoam na estrada", "Destino", "ada"),
    ("Céu abraça a imensidão", "Universo", "ão"),
    ("Esperança brota como flor", "Sentimento", "lor"),
    ("Marés contam sua história", "Mar", "ria"),
    ("Destino traça caminhos", "Destino", "hos"),
    ("Folhas dançam ao vento", "Natureza", "ento"),
    ("Coração pulsa forte", "Sentimento", "rte"),
    ("Astros guiam a jornada", "Universo", "ada"),
    ("Tempo renova as dores", "Reflexão", "res"),
    ("Brisa refresca a pele", "Natureza", "ele"),
    ("Horizonte se desfaz em cores", "Natureza", "res"),
    ("Sorrisos aquecem a alma", "Felicidade", "lma"),
    ("Chuva traz lembranças antigas", "Natureza", "gas"),
    ("Brisa leva os segredos", "Natureza", "dos"),
    ("Sol aquece cada instante", "Natureza", "nte"),
    ("Sombras dançam na parede", "Mistério", "ede"),
    ("Mar se agita em canção", "Mar", "ão"),
    ("Folhas sussurram memórias", "Reflexão", "ias"),
    ("Noite cobre os caminhos", "Natureza", "hos"),
    ("Vento espalha os desejos", "Natureza", "jos"),
    ("Estrelas guiam as promessas", "Universo", "sas"),
    ("Tempo apaga as pegadas", "Reflexão", "das"),
    ("Esperança floresce em silêncio", "Sentimento", "cio"),
    ("Saudade pesa no peito", "Sentimento", "ito"),
    ("Riso ilumina os passos", "Felicidade", "sos"),
    ("Lua se esconde nas nuvens", "Universo", "ens"),
    ("Dias passam sem aviso", "Tempo", "iso"),
    ("Sombras cobrem os mistérios", "Mistério", "ios"),
    ("Amor resiste às tempestades", "Amor", "des"),
    ("Destino escreve sua história", "Destino", "ria"),
    ("Pássaros cantam ao amanhecer", "Natureza", "cer"),
    ("Olhar reflete o infinito", "Sentimento", "ito"),
    ("Ondas abraçam a areia", "Mar", "eia"),
    ("Sonhos dançam entre as estrelas", "Sonhos", "las"),
    ("Alma se acalma no vento", "Sentimento", "ento"),
    ("Brisa toca os pensamentos", "Natureza", "tos"),
    ("Pegadas somem na estrada", "Natureza", "ada"),
    ("Sol desenha sombras na terra", "Natureza", "rra"),
    ("Noite se veste de prata", "Universo", "ata"),
    ("Tempestade anuncia mudanças", "Natureza", "ças"),
    ("Versos surgem na madrugada", "Poesia", "ada"),
    ("Caminhos guardam segredos", "Destino", "dos"),
    ("Neblina cobre as montanhas", "Natureza", "has"),
    ("Paixão arde como chama", "Amor", "ama"),
    ("Passado dorme na lembrança", "Reflexão", "ça"),
    ("Abraço dissolve o medo", "Sentimento", "edo"),
    ("Dias trazem novas cores", "Tempo", "res"),
    ("Fé constrói pontes invisíveis", "Reflexão", "eis"),
    ("Vento desenha melodias", "Natureza", "ias"),
    ("Chuva lava as cicatrizes", "Natureza", "zes"),
    ("Lua vigia os desejos", "Universo", "jos"),
    ("Coração canta em segredo", "Sentimento", "edo"),
    ("Silêncio sussurra verdades", "Reflexão", "des"),
    ("Destino traça seu próprio mapa", "Destino", "apa"),
    ("Ondas moldam cada história", "Mar", "ria"),
    ("Brisa traz recordações", "Natureza", "ões"),
    ("Astros contam seus mistérios", "Universo", "ios"),
    ("Dia renasce com esperança", "Natureza", "ça"),
    ("Palavras criam poesia", "Poesia", "sia"),
    ("Riso ilumina qualquer dor", "Felicidade", "dor"),
    ("Sombra guarda segredos antigos", "Mistério", "gos"),
    ("Céu acolhe cada sonho", "Universo", "nho"),
    ("Olhos escondem lembranças", "Sentimento", "ças"),
    ("Vento carrega promessas", "Natureza", "sas"),
    ("Amor floresce na espera", "Amor", "era"),
    ("Caminho ensina paciência", "Destino", "cia"),
    ("Estrada revela sua magia", "Destino", "gia"),
    ("Lábios murmuram poesia", "Sentimento", "sia"),
    ("Luar desenha novas fantasias", "Universo", "ias"),
    ("Dia repousa no horizonte", "Natureza", "nte"),
    ("Tempo suaviza feridas", "Reflexão", "das"),
    ("Sinos anunciam um recomeço", "Tempo", "eço"),
    ("Verdade brilha na alma", "Reflexão", "lma"),
    ("Paixão cresce como flor", "Amor", "lor"),
    ("Paz se espalha no tempo", "Sentimento", "mpo"),
    ("Sorrisos curam cicatrizes", "Felicidade", "zes"),
    ("Neblina esconde os caminhos", "Natureza", "hos"),
    ("Trovão rompe o silêncio", "Natureza", "cio"),
    ("Tempo revela cada lição", "Reflexão", "ão"),
    ("Mar ecoa histórias antigas", "Mar", "gas"),
    ("Destino sopra certezas", "Destino", "zas"),
    ("Pôr do sol colore o horizonte", "Natureza", "nte"),
    ("Noites guardam seus segredos", "Universo", "dos"),
    ("Silêncio revela a essência", "Reflexão", "cia"),
    ("Estrada se perde na neblina", "Destino", "ina"),
    ("Olhar desenha emoções", "Sentimento", "ões"),
    ("Tempo transforma saudades", "Reflexão", "des"),
    ("Brisa embala cada lembrança", "Natureza", "ça"),
    ("Amor se espalha pelo mundo", "Amor", "ndo"),
    ("Sol aquece os corações", "Natureza", "ões"),
    ("Lua dança sobre as águas", "Universo", "uas"),
    ("Destino escreve versos no vento", "Destino", "ento"),
    ("Silêncio ecoa no infinito", "Reflexão", "ito"),
    ("Tempo molda as memórias", "Reflexão", "ias"),
    ("Passos marcam a areia", "Destino", "eia"),
    ("Céu guarda mistérios ocultos", "Universo", "tos"),
    ("Esperança nasce entre flores", "Sentimento", "res"),
    ("Marés transformam as paisagens", "Mar", "ens"),
    ("Destino abre novas portas", "Destino", "tas"),
    ("Folhas dançam ao sabor do vento", "Natureza", "ento"),
    ("Coração pulsa em silêncio", "Sentimento", "cio"),
    ("Astros sussurram histórias antigas", "Universo", "gas"),
    ("Tempo renova as lembranças", "Reflexão", "ças"),
    ("Brisa refresca a tarde", "Natureza", "rde"),
    ("Horizonte se dissolve em cores", "Natureza", "res"),
    ("Sorrisos aquecem a alma", "Felicidade", "lma"),
    ("Chuva traz promessas distantes", "Natureza", "tes"),
    ("Coração bate em desatino", "Amor", "ino"),
    ("Teus olhos brilham como estrelas", "Amor", "las"),
    ("Em teus braços mora a calma", "Amor", "lma"),
    ("Nosso amor corre como rio", "Amor", "rio"),
    ("Teu perfume embriaga a alma", "Amor", "lma"),
    ("Sussurros doces na madrugada", "Amor", "ada"),
    ("Teus lábios trazem poesia", "Amor", "sia"),
    ("Meu peito arde em desejo", "Amor", "ejo"),
    ("Tua ausência é tempestade", "Amor", "ade"),
    ("Nosso beijo tem sabor de céu", "Amor", "éu"),
    ("Cada toque teu é chama", "Amor", "ama"),
    ("És a luz na minha estrada", "Amor", "ada"),
    ("Sentir teu cheiro me acalma", "Amor", "lma"),
    ("Teu amor é mar sereno", "Amor", "eno"),
    ("Palavras tuas são abrigo", "Amor", "igo"),
    ("No teu peito eu me perco", "Amor", "rco"),
    ("A saudade grita forte", "Amor", "rte"),
    ("Sem teus beijos, sou inverno", "Amor", "rno"),
    ("Teu sorriso é meu abrigo", "Amor", "igo"),
    ("Amar-te é voar sem medo", "Amor", "edo"),
    ("Tua voz embala sonhos", "Amor", "hos"),
    ("Meu olhar busca o teu", "Amor", "teu"),
    ("Em teus braços sou completo", "Amor", "eto"),
    ("No silêncio, teu nome ecoa", "Amor", "coa"),
    ("És a chama que me aquece", "Amor", "ece"),
    ("No teu abraço o tempo para", "Amor", "ara"),
    ("Caminho em teus sonhos leves", "Amor", "ves"),
    ("Sinto tua pele na brisa", "Amor", "isa"),
    ("A distância dói na alma", "Amor", "lma"),
    ("Entre versos, teu nome escrevo", "Amor", "evo"),
    ("Tuas promessas são estrelas", "Amor", "las"),
    ("Te amar é perder o chão", "Amor", "ão"),
    ("Ecos doces do teu riso", "Amor", "iso"),
    ("Teu olhar me desarma", "Amor", "rma"),
    ("Teu calor é minha casa", "Amor", "asa"),
    ("Nosso amor é mar revolto", "Amor", "olto"),
    ("Na tua ausência, sou sombra", "Amor", "bra"),
    ("Teu beijo é brisa suave", "Amor", "ave"),
    ("Teu toque apaga a dor", "Amor", "dor"),
    ("Teu nome vive em meu peito", "Amor", "eito"),
    ("Te espero em cada aurora", "Amor", "ora"),
    ("Tua lembrança me embriaga", "Amor", "aga"),
    ("No teu riso, encontro paz", "Amor", "az"),
    ("Nosso amor resiste ao tempo", "Amor", "mpo"),
    ("Cada verso tem teu nome", "Amor", "ome"),
    ("Nosso encontro foi destino", "Amor", "ino"),
    ("Minha alma dança em ti", "Amor", "ti"),
    ("Entre nós, só existe o infinito", "Amor", "ito"),
    ("O universo canta nosso amor", "Amor", "mor"),
    ("Amar-te é ser livre no vento", "Amor", "ento"),
    ("Sem ti, o mundo perde cor", "Amor", "cor"),
    ("Teus olhos são minha bússola", "Amor", "ola"),
    ("No teu abraço, sou imortal", "Amor", "tal"),
    ("O amor em nós sempre brilha", "Amor", "lha"),
    ("Teus gestos são poesia viva", "Amor", "iva"),
    ("No teu beijo, mora o verão", "Amor", "ão"),
    ("Tua voz é melodia doce", "Amor", "ce"),
    ("Cada toque teu é promessa", "Amor", "ssa"),
    ("Nosso amor não conhece fim", "Amor", "fim"),
    ("Nosso enlace é chama eterna", "Amor", "rna"),
    ("A vida sorri quando estás", "Amor", "tás"),
    ("No teu amor, encontro lar", "Amor", "lar"),
    ("Sem teu amor, sou inverno", "Amor", "rno"),
    ("Te amar é sempre renascer", "Amor", "cer"),
    ("És o sol que me ilumina", "Amor", "ina"),
    ("Nos teus braços, o mundo some", "Amor", "ome"),
    ("Nosso amor brilha como a lua", "Amor", "lua"),
    ("Cada instante teu é festa", "Amor", "sta"),
    ("Tua essência mora em mim", "Amor", "mim"),
    ("Teu toque é pura magia", "Amor", "gia"),
    ("Nosso amor nunca se apaga", "Amor", "aga"),
    ("Tua presença é meu refúgio", "Amor", "gio"),
    ("Em teu riso, sou criança", "Amor", "ça"),
    ("Nosso amor não tem fronteiras", "Amor", "ras"),
    ("Cada suspiro fala de ti", "Amor", "ti"),
    ("No teu olhar, o céu inteiro", "Amor", "eiro"),
    ("Sem teus braços, sou vazio", "Amor", "zio"),
    ("Te amar é dançar no vento", "Amor", "ento"),
    ("Tua pele é brisa quente", "Amor", "nte"),
    ("Teu nome pulsa em meu peito", "Amor", "eito"),
    ("Tua ausência é noite fria", "Amor", "ria"),
    ("Nosso amor escreve histórias", "Amor", "ias"),
    ("Cada suspiro teu é mel", "Amor", "mel"),
    ("Na tua voz, sou poesia", "Amor", "sia"),
    ("Teu beijo tem gosto de céu", "Amor", "éu"),
    ("Sem ti, o tempo se arrasta", "Amor", "sta"),
    ("Meu amor vive em teus versos", "Amor", "rsos"),
    ("No teu peito, sou abrigo", "Amor", "igo"),
    ("Teu abraço é mar sereno", "Amor", "eno"),
    ("Na tua luz, sou estrela", "Amor", "ela"),
    ("Nosso amor voa sem medo", "Amor", "edo"),
    ("A chuva canta sobre as folhas", "Natureza", "has"),
    ("O sol desponta entre as montanhas", "Natureza", "has"),
    ("A brisa sussurra entre os galhos", "Natureza", "lhos"),
    ("As ondas quebram sem pressa", "Natureza", "ssa"),
    ("A lua repousa sobre o rio", "Natureza", "rio"),
    ("Pássaros desenham melodias no céu", "Natureza", "éu"),
    ("O vento dança com as folhas", "Natureza", "has"),
    ("As estrelas piscam em segredo", "Natureza", "edo"),
    ("A terra respira entre as raízes", "Natureza", "zes"),
    ("Montanhas sussurram histórias antigas", "Natureza", "gas"),
    ("Teu olhar acende minha alma", "Amor", "lma"),
    ("Nosso amor é chama eterna", "Amor", "rna"),
    ("Cada beijo teu é melodia", "Amor", "dia"),
    ("Tua voz embala meus sonhos", "Amor", "hos"),
    ("Teu toque acalma meu peito", "Amor", "eito"),
    ("Nosso abraço é abrigo e lar", "Amor", "lar"),
    ("Teu sorriso ilumina meu dia", "Amor", "dia"),
    ("Teus lábios são fogo e doçura", "Amor", "ura"),
    ("Amar-te é viver poesia", "Amor", "sia"),
    ("No teu peito, encontrei meu mundo", "Amor", "ndo"),
    # Flor
    ("Uma rosa cresce entre espinhos", "Flor", "hos"),
    ("O perfume das flores adormece", "Flor", "ece"),
    ("Jardins brotam cores em festa", "Flor", "sta"),
    ("Os lírios dançam com o vento", "Flor", "ento"),
    ("As margaridas sorriem ao sol", "Flor", "sol"),
    ("Uma orquídea nasce em segredo", "Flor", "edo"),
    ("A primavera se pinta de cores", "Flor", "res"),
    ("Uma pétala toca a terra", "Flor", "rra"),
    ("As violetas perfumam a noite", "Flor", "ite"),
    ("Girassóis seguem a luz do dia", "Flor", "dia"),
    ("O relógio marca um último suspiro", "Morte", "iro"),
    ("A lápide guarda um nome esquecido", "Morte", "ido"),
    ("As sombras sussurram despedidas", "Morte", "das"),
    ("O silêncio cobre a estrada fria", "Morte", "ria"),
    ("Cinzas dançam sobre o vento", "Morte", "ento"),
    ("O tempo apaga todos os passos", "Morte", "sos"),
    ("O luto veste o mundo de preto", "Morte", "eto"),
    ("A saudade ecoa no vazio", "Morte", "zio"),
    ("O fim chega como um sussurro", "Morte", "rro"),
    ("Cada lágrima reflete uma despedida", "Morte", "ida"),
    ("A felicidade dança no ar", "Alegria", "ar"),
    ("Os risos preenchem cada canto", "Alegria", "nto"),
    ("O sol brilha em nossa pele", "Alegria", "ele"),
    ("O mundo canta em harmonia", "Alegria", "nia"),
    ("O sorriso ilumina as manhãs", "Alegria", "nhãs"),
    ("A festa se espalha no vento", "Alegria", "ento"),
    ("A euforia se espalha no tempo", "Alegria", "mpo"),
    ("O coração pulsa em cores vivas", "Alegria", "vas"),
    ("O amor colore os dias felizes", "Alegria", "zes"),
    ("Cada riso é um poema vivo", "Alegria", "ivo"),
    ("O relógio nunca para", "Tempo", "ara"),
    ("As horas voam sem aviso", "Tempo", "iso"),
    ("O tempo molda todas as almas", "Tempo", "lmas"),
    ("O passado sussurra histórias", "Tempo", "ias"),
    ("As memórias resistem ao vento", "Tempo", "ento"),
    ("Cada segundo guarda um segredo", "Tempo", "edo"),
    ("O tempo apaga marcas antigas", "Tempo", "gas"),
    ("Minutos correm como rios", "Tempo", "ios"),
    ("O destino escreve em linhas tortas", "Tempo", "rtas"),
    ("Os ponteiros dançam sem fim", "Tempo", "fim"),
    ("A brisa leve toca a montanha", "Natureza", "nha"),
    ("Os rios dançam sob a luz do luar", "Natureza", "uar"),
    ("No céu azul, as nuvens brincam", "Natureza", "cam"),
    ("O vento canta segredos antigos", "Natureza", "gos"),
    ("Folhas caem num balé dourado", "Natureza", "ado"),
    ("Teu olhar acende minha alma", "Amor", "lma"),
    ("Teus lábios têm sabor de mel", "Amor", "mel"),
    ("O amor floresce em cada toque", "Amor", "que"),
    ("Meu coração bate só por ti", "Amor", "ti"),
    ("No teu abraço, sou infinito", "Amor", "ito"),
    ("Uma rosa se abre na aurora", "Flor", "ora"),
    ("As pétalas sussurram segredos", "Flor", "dos"),
    ("O perfume das flores encanta", "Flor", "nta"),
    ("Os lírios dançam com o vento", "Flor", "ento"),
    ("Girassóis seguem o sol sem medo", "Flor", "edo"),
    ("", "", ""),
]